NAME = r'<a href=".*" class="user-info__fullname user-info__fullname_medium".*>(.*)</a>&'
NICKNAME = r'<a href=".*" class="user-info__nickname user-info__nickname_doggy".*>(.*)</a>'
USER_HUBS = r'<a href="(.*)" class="profile-section__user-hub ">(.*)</a>'
STATS = r'<div class="stacked-counter__value stacked-counter__value_.*">(.*)</div>'
SPEC = r'<div class="user-info__specialization">(.*)</div>'
RANKED = r'<a href=".*" class="defination-list__link">(\d*).*й</a>'
CITY = r'<a href=".*city.*" class="defination-list__link">(.*)</a>'
REGION = r'<a href=".*region.*" class="defination-list__link" title=".*">(.*)</a>'
COUNTRY = r'<a href=".*country=.*" class="defination-list__link">(.*)</a>'
DATES = r'<span class="defination-list__value">(\d{1,2} .*)</span>'
WORK = r'<a href="(.*company.*)" class="defination-list__link" title=".*">(.*)</a>'
ACTIVITY = r'<span class="defination-list__value">(\d{1,2}.\d{1,2}.\d{1,4}, \d{1,2}:\d{1,2})</span>'
COMPANIES = r'<a href="(.*)" class="list-snippet__title-link">(.*)</a>'
CONTRIB = r'<span class="rating-info__title" title=".*">(.*)</span>\s*<span class="rating-info__stat">(.*)</span>'
CONTRIB_LINK = r'<a href="(.*)" class="media-obj media-obj_link">'
POSTS = r'<a href="(.*)" class="post__title_link">(.*)</a>'
USER_COMMENTS = r'<a href="(.*)" class="icon_comment-anchor" title=".*">.*</a>'

AUTHOR = r'<span class="user-info__nickname user-info__nickname_small">(.*)</span>'
VOITINGS = r'<span class="voting-wjt__counter  voting-wjt__counter_positive  js-score".*>(.*)</span>'
FAVS_COUNT = r'<span class="bookmark__counter js-favs_count" title=".*">(\d*)</span>'
VIEWS = r'<span class="post-stats__views-count">(.*)</span>'
COM_COUNT = r'<span class="comments-section__head-counter" id="comments_count">\s*(.*)\s*</span>'
TAGS = r'<a href=".*" rel="tag" class="inline-list__item-link post__tag  ">(.*)</a>'
POST_HUBS = r'<a href="(.*)" class="inline-list__item-link hub-link " title=".*">(.*)</a>'
POST_COMMENTS = r'<a href="(.*)" class="icon_comment-anchor" title=".*">.*</a>'
