# Generated by Django 3.1.7 on 2021-03-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('date_birth', models.DateField(verbose_name='Дата рождения')),
                ('phone_number', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('city', models.CharField(max_length=25, verbose_name='Город')),
                ('site_1', models.CharField(max_length=250, verbose_name='Сайт 1')),
                ('site_2', models.CharField(max_length=250, verbose_name='Сайт 2')),
                ('site_3', models.CharField(max_length=250, verbose_name='Сайт 3')),
            ],
        ),
    ]
