# Generated by Django 3.1.7 on 2021-03-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='main',
            options={'verbose_name': 'Кандидат', 'verbose_name_plural': 'Кандидаты'},
        ),
        migrations.AddField(
            model_name='main',
            name='site_10',
            field=models.CharField(blank=True, max_length=250, verbose_name='Сайт 10'),
        ),
        migrations.AddField(
            model_name='main',
            name='site_4',
            field=models.CharField(blank=True, max_length=250, verbose_name='Сайт 4'),
        ),
        migrations.AddField(
            model_name='main',
            name='site_5',
            field=models.CharField(blank=True, max_length=250, verbose_name='Сайт 5'),
        ),
        migrations.AddField(
            model_name='main',
            name='site_6',
            field=models.CharField(blank=True, max_length=250, verbose_name='Сайт 6'),
        ),
        migrations.AddField(
            model_name='main',
            name='site_7',
            field=models.CharField(blank=True, max_length=250, verbose_name='Сайт 7'),
        ),
        migrations.AddField(
            model_name='main',
            name='site_8',
            field=models.CharField(blank=True, max_length=250, verbose_name='Сайт 8'),
        ),
        migrations.AddField(
            model_name='main',
            name='site_9',
            field=models.CharField(blank=True, max_length=250, verbose_name='Сайт 9'),
        ),
        migrations.AlterField(
            model_name='main',
            name='site_1',
            field=models.CharField(blank=True, max_length=250, verbose_name='Сайт 1'),
        ),
        migrations.AlterField(
            model_name='main',
            name='site_2',
            field=models.CharField(blank=True, max_length=250, verbose_name='Сайт 2'),
        ),
        migrations.AlterField(
            model_name='main',
            name='site_3',
            field=models.CharField(blank=True, max_length=250, verbose_name='Сайт 3'),
        ),
    ]
