# Generated by Django 3.1.7 on 2021-03-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210326_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='site_1',
            field=models.URLField(blank=True, max_length=250, verbose_name='Сайт 1'),
        ),
        migrations.AlterField(
            model_name='main',
            name='site_10',
            field=models.URLField(blank=True, max_length=250, verbose_name='Сайт 10'),
        ),
        migrations.AlterField(
            model_name='main',
            name='site_2',
            field=models.URLField(blank=True, max_length=250, verbose_name='Сайт 2'),
        ),
        migrations.AlterField(
            model_name='main',
            name='site_3',
            field=models.URLField(blank=True, max_length=250, verbose_name='Сайт 3'),
        ),
        migrations.AlterField(
            model_name='main',
            name='site_4',
            field=models.URLField(blank=True, max_length=250, verbose_name='Сайт 4'),
        ),
        migrations.AlterField(
            model_name='main',
            name='site_5',
            field=models.URLField(blank=True, max_length=250, verbose_name='Сайт 5'),
        ),
        migrations.AlterField(
            model_name='main',
            name='site_6',
            field=models.URLField(blank=True, max_length=250, verbose_name='Сайт 6'),
        ),
        migrations.AlterField(
            model_name='main',
            name='site_7',
            field=models.URLField(blank=True, max_length=250, verbose_name='Сайт 7'),
        ),
        migrations.AlterField(
            model_name='main',
            name='site_8',
            field=models.URLField(blank=True, max_length=250, verbose_name='Сайт 8'),
        ),
        migrations.AlterField(
            model_name='main',
            name='site_9',
            field=models.URLField(blank=True, max_length=250, verbose_name='Сайт 9'),
        ),
    ]
