# Generated by Django 3.1.7 on 2021-05-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210408_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='middleName',
        ),
        migrations.AddField(
            model_name='main',
            name='patronymic',
            field=models.CharField(blank=True, max_length=25, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='main',
            name='city',
            field=models.CharField(blank=True, max_length=25, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='main',
            name='date_birth',
            field=models.DateField(blank=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='main',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='main',
            name='lastName',
            field=models.CharField(max_length=25, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='main',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
    ]
