# Generated by Django 3.2.3 on 2021-06-24 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210513_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='main',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='main',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
